sudo: false
language: node_js
node_js:
- '6'
- '5'
- '4'
script: set -e; mkdir -p build; npm run build; if [[ $(node --version) == v6* ]];
  then npm run coveralls; chmod u+x scripts/travis-deploy.sh; ./scripts/travis-deploy.sh;
  fi
env:
  global:
  - GH_REF: github.com/ractivejs/ractive.git
  - CDN_REF: github.com/ractivejs/cdn.ractivejs.org.git
  - secure: nlnXJW/imf/w6qdTd7UCpRqLhLioxU6fllJPbP1DZr/9rp44HNVSPNxxGrA808VDXQ1ccpXBxIV9mgIi4Q/G0FUILA5NsSGYdQE00A+Lw3qnvv5FQ7Qoux44BKYi4L1W+4Zi3NEr7TAL+/dHCAk5k/ZKLTCCxiziAEw3M+akE4A=
  - secure: W+gKWvHDgHXI+1tARD+QxFbgjxhU6AN9Fn40v4u5lNwjOXuxcgH6UMK9YaePPaFAO62H7EeUZdbeghn3qTixR6naUewdq+U50U814Y6gcXhAAHcPoHBkbUOUAuUWbp3saNcECOMUlLsiOl2S+A8iMvwEFqz84O2Pdwj68TmKJHw=
  - secure: iUqcSoWpThxocqJsoJAhbEZeQWibsM1V6PsQN9dGOS2DhaEcPaKg8yz7wL1V+rNKLzBPo9p41BPT6ij8SeVVMJ8lsvjJgptPItoPjeS9CQ9vzQ/aC/I+56mD86I7aMwkFciZXWVYYRPZ9u/5qaqUcsKyn6LVz41CZfFiJXCbm64=
  - secure: lx6U8QucHZnZQlF5qH4W+crc0ip05wCoFm+BAvJXuLHEtBjRQS1LWVEVJxKHBk7A9rm6fMEbAFo0unPCRiLNWpcfR+srzVlut+Ha+aQuQVI1dMyQZ+ngoi+s7BvL3pCH/Wp2RSTL2tkyCsVin0JVxYa6TAif1fyVa3P1BmVvdGw=
branches:
  only:
  - 0.8
  - dev
